# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

h1plgc <- function(b, x, d, g) {
    .Call(`_raschreg_h1plgc`, b, x, d, g)
}

hbc <- function(x, d, b, a) {
    .Call(`_raschreg_hbc`, x, d, b, a)
}

hbc_skew <- function(x, d, b, a, nu) {
    .Call(`_raschreg_hbc_skew`, x, d, b, a, nu)
}

huc <- function(x, d, a, b, z, beta) {
    .Call(`_raschreg_huc`, x, d, a, b, z, beta)
}

raschlik <- function(d, X, bmax, a, np) {
    .Call(`_raschreg_raschlik`, d, X, bmax, a, np)
}

raschlik_skew <- function(d, X, bmax, a, np, nu) {
    .Call(`_raschreg_raschlik_skew`, d, X, bmax, a, np, nu)
}

raschreglik <- function(d, a, X, bmax, Z, beta) {
    .Call(`_raschreg_raschreglik`, d, a, X, bmax, Z, beta)
}

